"use server";

import { revalidatePath } from "next/cache";
import { getTranslations } from "next-intl/server";
import { createClient } from "@/lib/supabase/server";
import { requireUser } from "@/lib/auth/dal";
import { logActivity } from "@/lib/activity";
import type { FormState } from "@/app/actions/auth";

const ALLOWED_DAYS = new Set([1, 3, 7, 14, 30]);

export async function createFolderShareLink(
  _prev: FormState,
  formData: FormData,
): Promise<FormState> {
  const user = await requireUser();
  const t = await getTranslations("Shares");

  const clientId = String(formData.get("client_id") ?? "");
  const days = Number(formData.get("days"));

  if (!clientId) return { error: t("errMissingFolder") };
  if (!ALLOWED_DAYS.has(days)) {
    return { fieldErrors: { days: [t("errDuration")] } };
  }

  const expiresAt = new Date(Date.now() + days * 86_400_000).toISOString();

  const supabase = await createClient();
  // RLS insert check requires created_by = auth.uid() and access to a project
  // under the client. The token is generated by the column default.
  const { data, error } = await supabase
    .from("folder_share_links")
    .insert({
      client_id: clientId,
      created_by: user.id,
      expires_at: expiresAt,
    })
    .select("id")
    .single();

  if (error || !data) {
    return { error: error?.message ?? t("errCreateFailed") };
  }

  await logActivity(supabase, {
    action: "folder_share.created",
    entityType: "client",
    entityId: clientId,
    metadata: { share_id: data.id, days },
  });

  revalidatePath(`/documents/clients/${clientId}`);
  return { success: t("created", { count: days }) };
}

export async function revokeFolderShareLink(formData: FormData): Promise<void> {
  await requireUser();

  const id = String(formData.get("id") ?? "");
  const clientId = String(formData.get("client_id") ?? "");
  if (!id) return;

  const supabase = await createClient();
  // RLS update policy allows only admins or the link creator.
  await supabase
    .from("folder_share_links")
    .update({ revoked_at: new Date().toISOString() })
    .eq("id", id)
    .is("revoked_at", null);

  await logActivity(supabase, {
    action: "folder_share.revoked",
    entityType: "client",
    entityId: clientId,
    metadata: { share_id: id },
  });

  if (clientId) revalidatePath(`/documents/clients/${clientId}`);
}
