"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { requireUser } from "@/lib/auth/dal";
import { logActivity } from "@/lib/activity";
import type { FormState } from "@/app/actions/auth";

const ALLOWED_DAYS = new Set([1, 3, 7, 14, 30]);

export async function createShareLink(
  _prev: FormState,
  formData: FormData,
): Promise<FormState> {
  const user = await requireUser();

  const documentId = String(formData.get("document_id") ?? "");
  const days = Number(formData.get("days"));

  if (!documentId) return { error: "Missing document." };
  if (!ALLOWED_DAYS.has(days)) {
    return { fieldErrors: { days: ["Choose a valid duration"] } };
  }

  const expiresAt = new Date(Date.now() + days * 86_400_000).toISOString();

  const supabase = await createClient();
  // RLS insert check requires created_by = auth.uid() and access to the
  // document's project. The token is generated by the column default.
  const { data, error } = await supabase
    .from("share_links")
    .insert({
      document_id: documentId,
      created_by: user.id,
      expires_at: expiresAt,
    })
    .select("id")
    .single();

  if (error || !data) {
    return { error: error?.message ?? "Could not create the share link." };
  }

  await logActivity(supabase, {
    action: "share.created",
    entityType: "document",
    entityId: documentId,
    metadata: { share_id: data.id, days },
  });

  revalidatePath(`/documents/${documentId}`);
  return { success: `Share link created, valid for ${days} day(s).` };
}

export async function revokeShareLink(formData: FormData): Promise<void> {
  await requireUser();

  const id = String(formData.get("id") ?? "");
  const documentId = String(formData.get("document_id") ?? "");
  if (!id) return;

  const supabase = await createClient();
  // RLS update policy allows only admins or the link creator.
  await supabase
    .from("share_links")
    .update({ revoked_at: new Date().toISOString() })
    .eq("id", id)
    .is("revoked_at", null);

  await logActivity(supabase, {
    action: "share.revoked",
    entityType: "document",
    entityId: documentId,
    metadata: { share_id: id },
  });

  if (documentId) revalidatePath(`/documents/${documentId}`);
}
